name: publish
on:
  push:
    branches:
      - develop
      - 'release/**'
  pull_request:
    branches:
      - develop
      - 'release/**'

jobs:
  publish:
    name: publish

    runs-on: windows-latest

    env:
      VERSION: ''

    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Generate Version
      shell: pwsh
      run: |
        $version = .\.github\workflows\Get-Version.ps1 ${{ github.run_number }} ${{ github.ref }} ${{ github.base_ref}}
        echo "VERSION=$version" >> $env:GITHUB_ENV
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Set up Poetry
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: 1.1.10
    - name: Install dependencies
      run: poetry install
    - name: Run unit tests
      run: poetry run pytest
    - name: Build executable
      run: poetry run pyinstaller -F continuousintegrationdemo.spec
    - name: Upload executable
      uses: actions/upload-artifact@v2
      with:
        name: continuousintegrationdemo.${{ env.VERSION }}.exe
        path: dist/continuousintegrationdemo.exe
        if-no-files-found: error